# commit to be tagged for new release
commit = "HEAD"

project_name = "registry"
github_repo = "distribution/distribution"

# previous release
previous = "v2.7.1"

pre_release = false

preface = """\
The 2.7.2 registry release has been a long time overdue.
This is a patch release that improves docs, CI builds
and adds a few bug fixes.

See changelog below for full list of changes

### Bugfixes

* Close the io.ReadCloser from storage driver [#3370](https://github.com/distribution/distribution/pull/3370)
* Remove empty Content-Type header [#3297](https://github.com/distribution/distribution/pull/3297)
* Make ipfilteredby not required  [#3088](https://github.com/distribution/distribution/pull/3088)

### CI build

* First draft of actions based ci [#3347](https://github.com/distribution/distribution/pull/3347)
* Fix vndr and check [#3001](https://github.com/distribution/distribution/pull/3001)

### Documentation

* Add redirect for old URL [#3197](https://github.com/distribution/distribution/pull/3197)
* Fix broken table [#3073](https://github.com/distribution/distribution/pull/3073)
* Adding deprecated schema instructions  [#2987](https://github.com/distribution/distribution/pull/2987)

### Storage drivers

* S3 Driver: add support for ceph radosgw [#3119](https://github.com/distribution/distribution/pull/3119)

### Dependency Changes

This release has no dependency changes
"""
